class SourceCharacter {}
class InputElementDiv {}
class InputElementRegExp {}
class InputElementRegExpOrTemplateTail {}
class InputElementTemplateTail {}
class WhiteSpace {}
class LineTerminator {}
class LineTerminatorSequence {}
class Comment {}
class MultiLineComment {}
class MultiLineCommentChars {}
class PostAsteriskCommentChars {}
class PostAsteriskCommentChar {}
class MultiLineNotForwardSlashOrAsteriskChar {}
class SingleLineComment {}
class SingleLineCommentChars {}
class SingleLineCommentChar {}
class CommonToken {}
class IdentifierName {}
class IdentifierStart {}
class IdentifierPart {}
class UnicodeIDStart {}
class UnicodeIDContinue {}
class ReservedWord {}
class Punctuator {}
class OptionalChainingPunctuator {}
class OtherPunctuator {}
class DivPunctuator {}
class RightBracePunctuator {}
class NullLiteral {}
class BooleanLiteral {}
class NumericLiteral {}
class DecimalBigIntegerLiteral {}
class NonDecimalIntegerLiteral {}
class BigIntLiteralSuffix {}
class DecimalLiteral {}
class DecimalIntegerLiteral {}
class DecimalDigits {}
class DecimalDigit {}
class NonZeroDigit {}
class ExponentPart {}
class ExponentIndicator {}
class SignedInteger {}
class BinaryIntegerLiteral {}
class BinaryDigits {}
class BinaryDigit {}
class OctalIntegerLiteral {}
class OctalDigits {}
class OctalDigit {}
class HexIntegerLiteral {}
class HexDigits {}
class HexDigit {}
class StringLiteral {}
class DoubleStringCharacters {}
class SingleStringCharacters {}
class SingleStringCharacter {}
class DoubleStringCharacter {}
class LineContinuaton {}
class EscapeSequence {}
class CharacterEscapeSequence {}
class SingleEscapeSequence {}
class NonEscapeCharacter {}
class EscapeCharacter {}
class HexEscapeSequence {}
class UnicodeEscapeSequence {}
class Hex4Digits {}
class RegularExpressionLiteral {}
class RegularExpressionBody {}
class RegularExpressionChars {}
class RegularExpressionFirstChar {}
class RegularExpressionChar {}
class RegularExpressionBackslashSequence {}
class RegularExpressionNonTerminator {}
class RegularExpressionClass {}
class RegularExpressionClassChars {}
class RegularExpressionClassChar {}
class RegularExpressionFlags {}
class Template {}
class NoSubstitutionTemplate {}
class TemplateHead {}
class TemplateSubstitutionTail {}
class TemplateMiddle {}
class TemplateTail {}
class TemplateCharacters {}
class TemplateCharacter {}
class NotEscapeSequence {}
class NotCodePoint {}
class CodePoint {}
class IdentifierReference {}
class BindingIdentifier {}
class LabelIdentifier {}
class Identifier {}
class PrimaryExpression {}
class CoverParenthesizedExpressionAndArrowParameterList {}
class ParenthesizedExpression {}
class Literal {}
class ArrayLiteral {}
class ElementList {}
class Elison {}
class SpreadElement {}
class ObjectLiteral {}
class PropertyDefinitionList {}
class PropertyDefinition {}
class PropertyName {}
class LiteralPropertyName {}
class ComputedPropertyName {}
class CoverInitializedName {}
class Initializer {}
class TemplateLiteral {}
class SubstitutionTemplate {}
class TemplateSpans {}
class TemplateMiddleList {}
class MemberExpression {}
class SuperProperty {}
class MetaProperty {}
class NewTarget {}
class ImportMeta {}
class NewExpression {}
class CallExpression {}
class CallMemberExpression {}
class SuperCall {}
class ImportCall {}
class Arguments {}
class ArgumentList {}
class OptionalExpression {}
class LeftHandSideExpression {}
class UpdateExpression {}
class UnaryExpression {}
class ExponentiationExpression {}
class MultiplicativeExpression {}
class MultiplicativeOperator {}
class AdditiveExpression {}
class ShiftExpression {}
class RelationalExpression {}
class EqualityExpression {}
class BitwiseANDExpression {}
class BitwiseXORExpression {}
class BitwiseORExpression {}
class LogicalANDExpression {}
class LogicalORExpression {}
class CoalesceExpression {}
class CoalesceExpressionHead {}
class ConditionalExpression {}
class AssignmentExpression {}
class AssignmentOperator {}
class AssignmentPattern {}
class ObjectAssignmentPattern {}
class ArrayAssignmentPattern {}
class AssignmentRestProperty {}
class AssignmentPropertyList {}
class AssignmentElementList {}
class AssignmentElisonElement {}
class AssignmentProperty {}
class AssignmentElement {}
class AssignmentRestElement {}
class DestructuringAssignmentTarget {}
class Expression {}
class Statement {}
class Declaration {}
class HoistableDeclaration {}
class BreakableStatement {}
class BlockStatement {}
class Block {}
class StatementList {}
class StatementListItem {}
class LexicalDeclaration {}
class LetOrConst {}
class BindingList {}
class LexicalBinding {}
class VariableStatement {}
class VariableDeclarationList {}
class VariableDeclaration {}
class BindingPattern {}
class ObjectBindingPattern {}
class ArrayBindingPattern {}
class BindingRestProperty {}
class BindingPropertyList {}
class BindingElementList {}
class BindingElisonElement {}
class BindingProperty {}
class BindingElement {}
class SingleNameBinding {}
class BindingRestElement {}
class EmptyStatement {}
class IfStatement {}
class IterationStatement {}
class ForDeclaration {}
class ForBinding {}
class ContinueStatement {}
class BreakStatement {}
class ReturnStatement {}
class WithStatement {}
class SwitchStatement {}
class CaseBlock {}
class CaseClauses {}
class CaseClause {}
class DefaultClause {}
class LabelledStatement {}
class LabelledItem {}
class ThrowStatement {}
class TryStatement {}
class Catch {}
class Finally {}
class CatchParameter {}
class DebuggerStatement {}
class FunctionDeclaration {}
class FunctionExpression {}
class UniqueFormalParameters {}
class FormalParameters {}
class FormalParameterList {}
class FunctionRestParameter {}
class FormalParameter {}
class FunctionBody {}
class FunctionStatementList {}
class ArrowFunction {}
class ArrowParameters {}
class ConciseBody {}
class ExpressionBody {}
class ArrowFormalParameters {}
class AsyncArrowFunction {}
class AsyncConciseBody {}
class AsyncArrowBBindingIdentifier {}
class CoverCallExpressionAndAsyncArrowHead {}
class AsyncArrowHead {}
class MethodDefinition {}
class PropertySetParameterList {}
class GeneratorMethod {}
class GeneratorDeclaration {}
class GeneratorExpression {}
class GeneratorBody {}
class YieldExpression {}
class AsyncGeneratorMethod {}
class AsyncGeneratorDeclaration {}
class AsyncGeneratorExpression {}
class AsyncGeneratorBody {}
class AsyncFunctionDeclaration {}
class AsyncFunctionExpression {}
class AsyncMethod {}
class AsyncFunctionBody {}
class AwaitExpression {}
class ClassDeclaration {}
class ClassExpression {}
class ClassTail {}
class ClassHeritage {}
class ClassBody {}
class ClassElementList {}
class ClassElement {}
class Script {}
class ScriptBody {}
class Module {}
class ModuleBody {}
class ModuleItemList {}
class ModuleItem {}
class ImportDeclaration {}
class ImportClause {}
class ImportedDefaultBinding {}
class NameSpaceImport {}
class NamedImports {}
class FromClause {}
class ImportsList {}
class ModuleSpecifier {}
class ImportedBinding {}
class ExportDeclaration {}
class ExportFromClause {}
class NamedExports {}
class ExportsList {}
class ExportSpecifier {}
class StrNumericLiteral {}
class StrWhiteSpace {}
class StrWhiteSpaceChar {}
class StrNumericLiteral {}
class StrDecimalLiteral {}
class StrUnsignedDecimalLiteral {}
class uri {}
class uriCharacters {}
class uriCharacter {}
class uriReserved {}
class uriUnescaped {}
class uriEscaped {}
class uriAlpha {}
class uriMark {}
class Pattern {}
class Disjunction {}
class Alternative {}
class Term {}
class Assertion {}
class Quantifier {}
class QuantifierPrefix {}
class Atom {}
class SyntaxCharacter {}
class AtomEscape {}
class CharacterEscape {}
class ControlEscape {}
class ControlLetter {}
class GroupSpecifier {}
class GroupName {}
class RegExpIdentifierName {}
class RegExpIdentifierStart {}
class RegExpUnicodeEscapeSequence {}
class LeadSurrogate {}
class TrailSurrogate {}
class NonSurrogate {}
class IdentityEscape {}
class DecimalEscape {}
class CharacterClassEscape {}
class UnicodePropertyValueExpression {}
class UnicodePropertyName {}
class UnicodePropertyNameCharacters {}
class UnicodePropertyValue {}
class UnicodePropertyNameOrValue {}
class UnicodePropertyValueCharacters {}
class UnicodePropertyValueCharacter {}
class UnicodePropertyNameCharacter {}
class CharacterClass {}
class ClassRanges {}
class NonEmptyClassRanges {}
class NonEmptyClassRangesNoDash {}
class ClassAtom {}
class ClassAtomNoDash {}
class ClassEscape {}